# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
sphinx:
  configuration: docs/conf.py
python:
  # Keep in sync with docs build CI job.
  version: "3.11"
  install:
    - requirements: docs/requirements.txt
