# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
sphinx:
  configuration: docs/conf.py
build:
  os: ubuntu-22.04
  tools:
    # Keep in sync with docs build CI job.
    python: "3.11"
python:
  install:
    - requirements: docs/requirements.txt
