name: Docs
on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}

jobs:
  setup-pages:
    name: Setup Pages
    runs-on: ubuntu-latest
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v2

  build:
    name: Build Sphinx Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: docs/requirements.txt
      - name: Install dependencies
        run: pip install --require-hashes -r docs/requirements.txt
      - name: Build docs
        run: sphinx-build -W -b html docs docs/_build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_build

  publish:
    needs:
      - build
      - setup-pages
    name: Publish docs on Github Pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      # To verify the deployment originates from an appropriate source.
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          preview: true
